name: Sample

on:
  push:
    branches: [main]

jobs:
  checkout:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: basic
          path: .

  run_test:
    needs: checkout

    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: basic
          path: .

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

  run_build:
    needs: run_test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: basic
          path: .

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  deploy-to-main:
    needs: run_build
    runs-on: ubuntu-latest
    environment: main
