name: Basic CI/CD

on:
  push:
    branches: [main]

jobs:
  # Jobs
  checkoutAndUploadArtifacts:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    # Checkout | Clone the repo
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - run: 'Cloning the repository...'

      # Setup node
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 24

      # Upload artifacts | Upload cloned repository to VM
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: 'basic-artifact'
          path: .
      - run: 'Uploading cloned repository...'

  # deploying-staging:
  #   needs: build
  #   environment: staging
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Deploying to staging..."

  # deploying-production:
  # needs: deploying-staging
  # environment: production
  # runs-on: ubuntu-latest
  # steps:
  # - run: echo "Deploying to production"
